### ISSUE TITLE
How to disable animation

### ISSUE THREAD

**Issue by wachd** [yshui/picom#321]
Arch, Openbox

I don't know what are you doing but, it said I can't use compton from now. 
if tried --no-fading-openclose but it still animates when I'm switching between workspaces

**Comment by mighty9245** [comment]
what do you mean under "it said I can't use compton from now"? you probably encountered a deprecation message since this fork of compton is now called picom.

this animation on opening/closing windows and on switching workspaces is called fading and if you want to disable it probably setting `fading` option to `false` will be enough.

**Comment by yshui** [comment]
switching between workspaces is not open or close, so it's not affected by the `--no-fading-openclose` option.
