### ISSUE TITLE
Feature request: Reload config with D-Bus

### ISSUE THREAD

**Issue by jluttine** [yshui/picom#380]
Hi, and thanks for maintaining picom! I have a small(?) feature request: Add a D-Bus message that can be sent to picom so that it reloads config from the given file. So, after I've updated my config file `~/my-picom-config`, I could just tell picom to read that file and reconfigure itself. Or maybe this is already supported as D-Bus methods are undocumented?

**Comment by mighty9245** [comment]
stable: picom reinitializes itself on SIGUSR1 (`pkill -USR1 picom`)
next: picom watches its config file and reinitializes itself on changes

**Comment by jluttine** [comment]
Ah, great! Thanks!

**Comment by jluttine** [comment]
Hmm.. Using `pkill -USR1 picom` stops the screen from updating. Well, the mouse cursor moves, nothing else updates on the screen. If I then kill it entirely with `pkill picom` then everything I did shows up instantly. Using i3 with very minimal picom configuration with just `backend="glx"`. It works with `backend="xrender"` but then some other stuff doesn't work (e.g., xsecurelock).

**Comment by jluttine** [comment]
Maybe related: https://github.com/yshui/picom/issues/306

Well, anyway, if I can't make it work, I'll open another proper issue about that.

**Comment by mighty9245** [comment]
ah, yes, there was an issue about this and you already found it :) 

looks like there is no *decent* way to achieve the behavior you want on the latest picom release (i assume that you're using picom v7.5 since you encountered this bug), so you either have to use picom built from the latest commit (`picom-git` package from aur, for example if you're on arch) or have to wait for the new release (looks like this should happen soon and i'm waiting for it as well, since it will fix some annoying bugs and add some nice features).

**Comment by jluttine** [comment]
Thanks, not a problem to use the latest commit as I'm using NixOS. Package modifications/patching are very simple to do. Assuming the latest commit is relatively stable and working otherwise. :slightly_smiling_face:

**Comment by jluttine** [comment]
Yes, I can confirm the issue is fixed in `next` branch. :+1:
