### ISSUE TITLE
Using blur theme with picom on an old computer

### ISSUE THREAD

**Issue by Joe23232** [yshui/picom#398]
If on an old computer, I used `awesome` Window Manager and I use `picom` as my compositor, and I decided to use a slight blur theme to the background of the windows, would it cause a huge overhead and cause high CPU usage when moving the windows around?

I heard from a friend that they used `compton` and they had this issue, so with `picom` (as it is a fork of `compton`) would the same issue occur?

**Comment by Finxert** [comment]
Why don't you try it and see if it's a real issue instead of opening an issue that you are not sure even exists in picom?

**Comment by Joe23232** [comment]
@Finxert Yeah I haven't even installed Linux yet. But yeah now I know that a lot of people on Reddit are complaining about performance issues when using the blur theme which is a bit unfortunate :/

**Comment by Finxert** [comment]
afaik the dual kawase filter picom uses is more efficient at higher blur strengths and tryone-comptons single kawase is more efficient at lower blur strengths.

I don't think your machine would have performance issues with either of these unless it's really ancient. tbh I realized lower blur settings look bad and it's better to run opacity alone, so I don't think it's too dramatic of an issue.

Still though I don't think this place is appropriate to open "issues" like theses, especially when you don't even have a linux system. I'd ask this on some forum rather than in a place where real bugs are meant to be reported.

**Comment by jallbrit** [comment]
@Joe23232 please close this issue.
