### ISSUE TITLE
window movement not in sync with cursor

### ISSUE THREAD

**Issue by arking7** [yshui/picom#416]
### Platform
Debian Sid amd64

### GPU, drivers, and screen setup
Intel HD 530 (6700K), kernel modesetting driver 1.20.8, one monitor connected by onboard DP

xf86-video-intel 2.99.917+git20200226-1

name of display: :0.0
display: :0 screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
Vendor: Intel (0x8086)
Device: Mesa Intel(R) HD Graphics 530 (SKL GT2) (0x1912)
Version: 20.0.6
Accelerated: yes
Video memory: 3072MB
Unified memory: yes
Preferred profile: core (0x1)
Max core profile version: 4.6
Max compat profile version: 4.6
Max GLES1 profile version: 1.1
Max GLES[23] profile version: 3.2
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) HD Graphics 530 (SKL GT2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 20.0.6
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6 (Compatibility Profile) Mesa 20.0.6
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 20.0.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

### Environment
xfce4, with picom as default compositor, xfwm4 as window manager only

### picom version
v8 (vgit-e553e)

### Configuration:
shadow = true;
shadow-radius = 15;
shadow-offset-x = -7;
shadow-offset-y = -7;
shadow-exclude = [
  #"name = 'Notification'",
  #"_GTK_FRAME_EXTENTS@:c",
  "class_g = 'Conky'",
  "class_g ?= 'Notify-osd'",
  "class_g = 'Cairo-clock'",
  "class_g = 'Telegram'"
];
fading = false
fade-in-step = 0.03;
fade-out-step = 0.03;
inactive-opacity = .99;
frame-opacity = 0.7;
inactive-opacity-override = false;
active-opacity = .99
focus-exclude = [ "class_g = 'Cairo-clock'" ];
blur-method = "gaussian"
blur-strength = 3
blur-background-frame = false
blur-background-exclude = [
  #"_GTK_FRAME_EXTENTS@:c",
  #"window_type = 'desktop'",
  "window_type = 'dock'"
];
backend = "glx";
vsync = true
mark-wmwin-focused = true;
mark-ovredir-focused = true;
detect-rounded-corners = true;
detect-client-opacity = true;
refresh-rate = 0
unredir-if-possible = true;
detect-transient = true
detect-client-leader = true
glx-no-stencil = true
glx-no-rebind-pixmap = true
glx-copy-from-front = false;
glx-swap-method = "copy";
use-damage = true
log-level = "warn";
wintypes:
{
  tooltip = { fade = true; shadow = true; opacity = 0.75; focus = true; full-shadow = false; };
  dock = { shadow = false; }
  dnd = { shadow = false; }
  popup_menu = { opacity = 0.8; }
  dropdown_menu = { opacity = 0.8; }
};

### Steps of reproduction
move a window

### Expected behavior
window moving with cursor

### Current Behavior
window movement not in sync with cursor, slightly jumps around the cursor

### Stack trace
none

### Other details
It took me some time to realize what exactly is happening, I thought it was performance problem at first, however after I read an issue #26 on github,  I understood that it was about the window's movement.

Disable vsync or setting "vblank_mode" to 0 make no difference, it seems like a chronical problem with Intel GPU.

[Screencast 2020-05-20 18:04:07.mp4.zip](https://github.com/yshui/picom/files/4656084/Screencast.2020-05-20.18.04.07.mp4.zip)

**Comment by Ropid** [comment]
The window cannot stick exactly to the mouse pointer. There will always be at least one frame delay. This is because of how Vsync works compared to how the mouse pointer works.

The mouse pointer is not part of the picture. The graphics card adds the pointer to the picture when it sends the data to the monitor. The pointer can then have its own behavior and isn't tied to picom drawing the picture.

Vsync adds a delay to when the picture shows up on the monitor. The lowest this delay can be in theory is one frame. In practice this can be more than one frame.

I'm using the amdgpu driver here. That theoretical best possible one frame of a delay I can only get with the `--experimental-backends` command line argument. I get a longer delay with the normal backends.

Both of the following command lines work for me to get no tearing and lowest possible delay:

```
picom --config /dev/null --experimental-backends --backend glx --vsync
picom --config /dev/null --experimental-backends --backend xrender --vsync
```

Microsoft Windows does something interesting to hide the problem: it disables the hardware mouse pointer while you are dragging windows. The Windows compositor draws the pointer while you move a window.

**Comment by arking7** [comment]
I think it is more of a performance problem, the latency reduced significantly after I switch graphic driver from modesetting to intel, sorry for the confusion.
