### ISSUE TITLE
Picom crashes when running on X configured with Xinerama

### ISSUE THREAD

**Issue by paulkass** [yshui/picom#439]
### Platform

Gentoo, kernel 5.4.48-gentoo, 

### GPU, drivers, and screen setup

intel and amd gpus, intel and amdgpu drivers respectively, two screens, one for each device combined with Xinerama

### Environment

I don't think it matters in this case, but dwm

### picom version

v8
### Configuration:
```
opacity-rule = [
  "90:class_g = 'st' && focused",
  "60:class_g = 'st' && !focused"
];
```

### Steps of reproduction

1. Set up a display with two screens, one for each device, and combine them with xinerama
2. Picom doens't start, running `picom -b` will crash

### Expected behavior
picom starts and `st` windows are transparent

### Current Behavior
`picom -b` crashes, `st` windows aren't transparent

### Stack trace

```
XIO:  fatal IO error 2 (No such file or directory) on X server ":1"
      after 63 requests (59 known processed) with 0 events remaining.
```

### Other details

I think this is because when using xinerama, the `randr` extension is not available. However, I don't know of a different way of having two independent monitors *on different devices* without using xinerama. Is there a way for picom to support xinerama?

**Comment by paulkass** [comment]
I also looked into the fact that it seems most projects are moving away from Xinerama, so I was wondering if there is an alternative solution where I can have two physical monitors, one managed by a different device (amd gpu and intel in my case), and have them combined in one screen? It doesn't seem like `picom` supports running on multiple screens (like `DISPLAY=":1.0"` and `DISPLAY=":1.1"`) and neither does `dwm`. Is there any workaround to this / plans to implement this in the future?

**Comment by Ropid** [comment]
Here's what I know about the modern alternative to Xinerama:

There are these arguments here for xrandr:

    --listproviders
    --setprovideroutputsource provider source

The man-page says this about `--setprovideroutputsource`:

> Set  source as the source of display output images for provider.  This is only possible if source and provider have the Source Output and Sink  Output  capabilities, respectively.   If  source  is  0x0, then provider is disconnected from its current output source.

This `--setprovideroutputsource` xrandr argument is the modern method to share a monitor between cards. There's an example in section "3. Reverse PRIME" in this article here:

https://wiki.archlinux.org/index.php/PRIME

About what this all means, first of all you have to configure Xorg so that it starts up on your AMD card and not on your Intel one. It should use the monitor connected to the AMD card by default, and it shouldn't use the monitor connected to the Intel GPU. When you then run `xrandr` to look at the situation, you will see just the one monitor connected to the AMD card.

Then next, you research `xrandr --listproviders` and you find out what names to use for `xrandr --setprovideroutputsource`. I think the order for you has to be first the Intel, then the AMD card. After you've run your `--setprovideroutputsource` command line, take another look at the `xrandr -q` output. xrandr should now have started showing the Intel GPU monitor outputs. You can then try to enable those outputs, you can run `xrandr --auto` and things should start up.

As far as I know, there's no way to set this `--setprovideroutputsource` stuff up through Xorg config files. It has to be done with an xrandr command line in a startup script like `~/.xprofile` or `~/.xinitrc`. The thing you can do in an Xorg config is just to make the AMD card the one that's used. I don't remember how to do that kind of config. Right now, I don't use a computer with two GPUs anymore.

**Comment by paulkass** [comment]
I got around my current problem by plugging both of my monitors into my AMD gpu for now, but I imagine that for anyone who comes across here the above comment might be useful.
