### ISSUE TITLE
Setting opacity to 1.0 doesn't make TOOLTIP WINTYPE opaque in GIMP/Firefox

### ISSUE THREAD

**Issue by jorgeluiscarrillo** [yshui/picom#526]
### Platform

Fedora 32
### GPU, drivers, and screen setup

Intel HD 3000 i915, mesa 20.1.10
```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel Open Source Technology Center (0x8086)
    Device: Mesa DRI Intel(R) HD Graphics 3000 (SNB GT2) (0x126)
    Version: 20.1.10
    Accelerated: yes
    Video memory: 1536MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 3.3
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.0
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 3000 (SNB GT2)
OpenGL core profile version string: 3.3 (Core Profile) Mesa 20.1.10
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.0 Mesa 20.1.10
OpenGL shading language version string: 1.30
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.0 Mesa 20.1.10
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
```
### Environment

i3wm
### picom version

```
**Version:** v8.1

### Extensions:

* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:

* Use Overlay: No (Another compositor is already running)
* Config file used: /home/user/.config/picom/picom.conf

### Drivers (inaccurate):

modesetting
````
### Configuration:
```
shadow = true;
shadow-radius = 12;
shadow-opacity = .4;
shadow-offset-x = -12;
shadow-offset-y = -7;
shadow-exclude = [
  "class_g = 'Firefox' && argb",
  "class_g = 'i3-frame'",
  "_GTK_FRAME_EXTENTS@:c"
];

backend = "glx";
vsync = true;
mark-wmwin-focused = true;
mark-ovredir-focused = true;
detect-rounded-corners = true;
detect-client-opacity = true;
refresh-rate = 0;
detect-transient = true;
detect-client-leader = true;
glx-no-stencil = true;
use-damage = true;
wintypes:
{
  tooltip       = { shadow = false; opacity = 1.0; };
  dock          = { shadow = false; };
  dnd           = { shadow = false; };
  menu          = { shadow = false; };
  dropdown_menu = { shadow = false; };
  popup_menu    = { shadow = false; };
  utility       = { shadow = false; };
};
```

### Steps of reproduction

1.
2.

### Expected behavior
Tooltip wintypes should be opaque when opacity is set to 1.0
### Current Behavior

When adjusting the opacity I can see the changes being reflected in Firefox/GIMP tooltips, but there is always some transparency even at 1.0. I tried another GTK app like Thunar, and it seems to be working as expected there.

**Comment by tryone144** [comment]
Out of curiosity: Does adding
```
opacity-rule = [
  "40:argb",
];
```
to your config change the opacity of Firefox/GIMP tooltips to 40%, but does not affect the ones in Thunar?
(On my system, this rule makes tooltips in Firefox and GIMP transparent, but not in Chromium and Nautilus. However tooltips are always fully opaque without this rule.)

You don't have any opacity rules in your config. Are you sure the slight transparency isn't caused by a theme?

**Comment by jorgeluiscarrillo** [comment]
> opacity-rule = [
>   "40:argb",
> ];

That makes my entire Firefox window (and some other apps) to 40% not just the tooltip. But you are right that Thunar, does not seem to be affected by this option at all.

And im sure its not a theme issue because if picom is not running, the tooltips go back to "normal" (fully opaque). Im using the default Adwaita theme.

**Comment by tryone144** [comment]
> That makes my entire Firefox window (and some other apps) to 40% not just the tooltip. But you are right that Thunar, does not seem to be affected by this option at all. Also GIMP is not affected either.

This is expected as it will turn all windows with an alpha channel transparent. GIMP tooltips should be transparent, but GIMP itself should not be. This is exactly the same behavior I see on my machine.

> And im sure its not a theme issue because if picom is not running, the tooltips go back to "normal" (fully opaque). Im using the default Adwaita theme.

If picom is not running, you don't have any compositor and no window will have any transparency. You need a compositor for transparency to work.

The transparency you see in those tooltips is stemming from the theme used. Firefox uses a slight transparent background for theirs (see [this post](https://www.reddit.com/r/FirefoxCSS/comments/8z8k3d/get_rid_of_tooltip_transparency/)). GIMP might use your system theme or one of its own, but the transparency is most likely also caused by the GTK theme. You might try and change your GTK theme to HighContrast which has fully opaque tooltips to check for yourself. If you want to have fully opaque tooltips you might have to look into [tweaking the GTK theme](https://blogs.gnome.org/mclasen/2014/05/06/tweaking-a-the-gtk-theme-using-css/).

**Comment by jorgeluiscarrillo** [comment]
> If picom is not running, you don't have any compositor and no window will have any transparency. You need a compositor for transparency to work.

Ok, this was the issue. I am coming from not using any compositing at all so I assumed that was the default behavior. I will look into those workarounds. Thanks for your help.
