### ISSUE TITLE
Zathura displays with white border when picom is running

### ISSUE THREAD

**Issue by toniz4** [yshui/picom#586]
### Platform

Linux gentoo 5.10.10-gentoo-x86_64-coffe #10 SMP Mon Jan 25 18:30:08 -03 2021 x86_64 Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz GenuineIntel GNU/Linux
### glxinfo:
```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel Open Source Technology Center (0x8086)
    Device: Mesa DRI Intel(R) HD Graphics 4000 (IVB GT2) (0x166)
    Version: 20.2.4
    Accelerated: yes
    Video memory: 1536MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.2
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.0
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 4000 (IVB GT2)
OpenGL core profile version string: 4.2 (Core Profile) Mesa 20.2.4
OpenGL core profile shading language version string: 4.20
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.0 Mesa 20.2.4
OpenGL shading language version string: 1.30
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.0 Mesa 20.2.4
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
```
### Intel driver:
xf86-video-intel-2.99.917_p20200515

### Environment

using xmonad 0.15

### picom version

**Version:** v8.2

### Extensions:

* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:

* Use Overlay: No (Another compositor is already running)
* Config file used: /home/cassio/.config/picom/picom.conf

### Drivers (inaccurate):

Intel
### Configuration:
```
vsync = true;

fade-delta = 3;
fade-in-step = 0.03
fade-out-step = 0.03
use-damage=true
frame-opacity = 1;

xrender-sync-fence = true
wintypes:
{
	notification = { fade = true }
}
```
### Steps of reproduction

1. Open zathura when running picom
2. Observe that the zathura border is always white

### Expected behavior
Zathura should have the same border as other windows, when picom is not running it works as intended:
![woPicom](https://user-images.githubusercontent.com/14265358/105849839-af566880-5fbf-11eb-8f9f-d08134752fd5.png)

### Current Behavior
When using picom the zathura border becomes white when is focused or unfocused, here is a screenshot of me focusing the zathura window, it should have a cyan border like the first example:
![wPicom](https://user-images.githubusercontent.com/14265358/105849978-e167ca80-5fbf-11eb-91aa-e81a3d631f45.png)

### Other details

it's compiled with all the USE flags on gentoo, except `test`.

**Comment by branwright1** [comment]
I'm having same problem, it's exists only when picom is running. I heard that it picom has problems with double borders from external script but those are from WM not scripts
Picom version 8.2  (from NixOS unstable channel), other windows aren't acting this bug. (look at discord)
![image](https://cdn.discordapp.com/attachments/670699013191761945/804476793188646942/unknown.png)

**Comment by kwand** [comment]
@branwright1 Could you attach your config file + hardware specs as well? (Or is it the same as the OP?)

I'm unable to reproduce this issue (though I'm on NVIDIA and i3 gaps - which may or may not have anything to do with this issue)

**Comment by branwright1** [comment]
> @branwright1 Could you attach your config file + hardware specs as well? (Or is it the same as the OP?)
> 
> I'm unable to reproduce this issue (though I'm on NVIDIA and i3 gaps - which may or may not have anything to do with this issue)

I'm using laptop with 1GB Intel HD 5500 GPU

Here is my config:
https://github.com/branwright1/non-flaked-nix/blob/master/.config/picom/picom.conf

**Comment by kwand** [comment]
@branwright1 Thanks. I've just tried running picom loading your config, and unfortunately, I'm still not able to reproduce the same behaviour. I suspect it may be either Intel or your DE; I'll have to try this on my laptop a bit later.

To confirm, the issue is that there are white/semi-transparent borders around Zathura? (Sorry if I got this wrong, it's a bit hard to tell since your screenshot is different from the OP's)

Settings-wise, have you tried setting `use-damage=false` (or does this cause performance issues for you?). I've seen that some of these issues might be residue from not redrawing certain parts with `use-damage=true`

**Comment by toniz4** [comment]
The issue aper

**Comment by toniz4** [comment]
The issue appeared in dwm and xmonad for me, and it's not a seme transparent border, but a white border.
I tried using the glx backend and use damage, but i still have the same issue

**Comment by kwand** [comment]
> The issue appeared in dwm and xmonad for me, and it's not a seme transparent border, but a white border.
> I tried using the glx backend and use damage, but i still have the same issue

I know. I was just confirming @branwright1's issue, since their screenshot seems to show a slightly different problem from yours.

Unfortunately, I don't think I'll be able to examine this further on my main machine. I'll probably need to install dwm or xmonad on my Intel iGPU laptop to investigate further.

**Comment by kwand** [comment]
Actually, I do have one more possible solution: have you tried the experimental backends? i.e `picom --daemon --experimental-backends`?

I've heard that there have been some fixes there, that may or may not fix your current issue.

**Comment by toniz4** [comment]
> @toniz4
> 
> Actually, I do have one more possible solution: have you tried the experimental backends? i.e `picom --daemon --experimental-backends`?
> 
> I've heard that there have been some fixes there, that may or may not fix your current issue.

I usually start picom like that, launching it with or without --experimental-backends will lead to the same issue.

**Comment by toniz4** [comment]
I tested this with xcompmgr and had the same issue, so it's possible this is a problem with zathura.

**Comment by Barbarossa93** [comment]
I think the transparency issue is related to this: https://github.com/yshui/picom/issues/285. It seems that this is possibly an issue with intel gpus and /or with certain window managers. I'm having the same problem as @branwright1 using an intel gpu laptop and with herbstluftwm. It's not impossible that it is an intrinsic problem with zathura however, however, since zathura doesn't have this problem in bspwm, I'm led to believe that it is a window manager issue.

**Comment by Barbarossa93** [comment]
As of https://github.com/herbstluftwm/herbstluftwm/commit/696afd4f1e4bc7860e4478820f6c69bb06220c76, this is no longer an issue for me in herbstluftwm

**Comment by toniz4** [comment]
@Barbarossa93 i applied the dwm patch referenced at that pull request and its working as intended, closing since it is a problem with the window manager, not picom.
