### ISSUE TITLE
Picom appears to be unmaintained

### ISSUE THREAD

**Issue by godalming123** [yshui/picom#757]
Is picom still maintained?

**Comment by Henryws** [comment]
Why would it not be?

**Comment by godalming123** [comment]
Just thought that if this was maintained a fork would have arised as the new default.

**Comment by kwand** [comment]
Why would that be? The last commit was made just a few hours ago.

If you're talking about releases: yes, a release hasn't been issued in quite a while. But there have been plenty of changes/improvements since then. Hence, I've been using the `picom-git` package in Arch for quite some time now. 

(Yes, it's unfortunate that using the `git` branch should be the recommended default for picom, instead of a packaged release, but this seems to be the case for a lot of open-source projects these days)

**Comment by godalming123** [comment]
Well when I opened his issue he last commit on master was a few months ago

**Comment by yshui** [comment]
@godalming123 I am busy for the past couple months and still am now, so I can't put much work into picom. But I am totally happy to review PRs, so if you have things you want to contribute please feel free.
